all:
  childeren:
    timeservers:
      hosts:
        ts01:
          ansible_user: root
          ansible_host: <ansiblenode0x.ansibleworkshop.sue.nl>
        ts02:
          ansible_user: root
          ansible_host: <ansiblenode0x.ansibleworkshop.sue.nl>
