---

# Repos and other required repos
chrony_required_packages: []

chrony_packages:
  - chrony

chrony_service_name: chronyd
chrony_configfile_path: /etc/chrony.conf

# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (http://www.pool.ntp.org/join.html).
# Type: list
chrony_config_server:
  - 0.nl.pool.ntp.org iburst
  - 1.nl.pool.ntp.org iburst
  - 2.nl.pool.ntp.org iburst
  - 3.nl.pool.ntp.org iburst

# Record the rate at which the system clock gains/losses time.
# Type: string
chrony_config_driftfile: /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
# Type: string
chrony_config_makestep: 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
# Type: boolean
chrony_config_rtcsync: yes

# Enable hardware timestamping on all interfaces that support it.
# Type: string
chrony_config_hwtimestamp: ''

# Increase the minimum number of selectable sources required to adjust
# the system clock.
# Type: integer
chrony_config_minsources: ''

# Allow NTP client access from local network.
# Type: cidr list
chrony_config_allow: []

# Serve time even if not synchronized to a time source.
# Type: integer
chrony_config_local_stratum: ''

# Specify file containing keys for NTP authentication.
# Type: string
chrony_config_keyfile: /etc/chrony.keys

# Specify directory for log files.
# Type: string
chrony_config_logdir: /var/log/chrony

# Select which information is logged.
# Type: space separated (measurements statistics tracking)
chrony_config_log: ''
