- name: testing variables
  debug:
    msg: "The variable is {{ file_operations }}"
  when: file_operations is defined

- name: file operation for {{ item.name }}
  user:
    access_time : "{{ item.access_time  | default(omit) }}"
    access_time_format : "{{ item.access_time_format  | default(omit) }}"
    attributes : "{{ item.attributes  | default(omit) }}"
    follow: "{{ item.follow  | default(omit) }}"
    force: "{{ item.system | default('no') }}"
    group: "{{ item.group   | default(omit) }}"
    mode: "{{ item.access_time_format  | default(omit) }}"
    modification_time: "{{ item.modification_time | default(omit) }}"
    modification_time_format: "{{ item.modification_time_format | default(omit) }}"
    owner : "{{ item.owner | default('no') }}"
    path: "{{ item.path  | default(omit) }}"
    recurse: "{{ item.recurse | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default('no') }}"
  loop: "{{ file_operations }}"
  loop_control:
    label: "{{ item.name }}"
  when: file_operations is defined
