webservers:
  hosts:
    web10:
      ansible_user: automator
      ansible_host: web10.of.worlds.com
      ansible_ssh_pass: "{{ web10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ web10_automator }}"
    web11:
      ansible_user: automator
      ansible_host: web11.of.worlds.com
      ansible_ssh_pass: "{{ web11_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ web11_automator }}"
    web12:
      ansible_user: automator
      ansible_host: web12.of.worlds.com
      ansible_ssh_pass: "{{ web12_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ web12_automator }}"
nfsservers:
  hosts:
    nfs10:
      ansible_user: automator
      ansible_host: nfs10.of.worlds.com
      ansible_ssh_pass: "{{ nfs10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ nfs10_automator }}"
    nfs11:
      ansible_user: automator
      ansible_host: nfs11.of.worlds.com
      ansible_ssh_pass: "{{ nfs11_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ nfs11_automator }}"
vault:
  hosts:
    vault10:
      ansible_user: automator
      ansible_host: vault10.of.worlds.com
      ansible_ssh_pass: "{{ vault10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ vault10_automator }}"
ftpservers:
  hosts:
    ftp10:
      ansible_user: automator
      ansible_host: ftp10.of.worlds.com
      ansible_ssh_pass: "{{ ftp10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ ftp10_automator }}"
mailservers:
  hosts:
    ms10:
      ansible_user: automator
      ansible_host: ms10.of.worlds.com
      ansible_ssh_pass: "{{ ms10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ ms10_automator}}"

keycloak:
  hosts:
    kc10:
      ansible_user: automator
      ansible_host: kc10.of.worlds.com
      ansible_ssh_pass: "{{ kc10_automator }}"
      ansible_become: True
      ansible_become_method: sudo
      ansible_become_password: "{{ kc10_automator }}"
