all:
  children:
    webservers:
      hosts:
        web20:
          ansible_user: automator
          ansible_host: web20.of.worlds.com
          ansible_ssh_pass: "{{ web20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ web20_automator }}"
      children:
        apache:
          hosts:
            web21:
              ansible_user: automator
              ansible_host: web21.of.worlds.com
              ansible_ssh_pass: "{{ web21_automator }}"
              ansible_become: True
              ansible_become_method: sudo
              ansible_become_password: "{{ web21_automator }}"
        nginx:
          hosts:
            web22:
              ansible_user: automator
              ansible_host: web22.of.worlds.com
              ansible_ssh_pass: "{{ web22_automator }}"
              ansible_become: True
              ansible_become_method: sudo
              ansible_become_password: "{{ web22_automator }}"
    nfsservers:
      hosts:
        nfs20:
          ansible_user: automator
          ansible_host: nfs20.of.worlds.com
          ansible_ssh_pass: "{{ nfs20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ nfs20_automator }}"
        nfs21:
          ansible_user: automator
          ansible_host: nfs21.of.worlds.com
          ansible_ssh_pass: "{{ nfs21_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ nfs21_automator }}"
    vault:
      hosts:
        vault20:
          ansible_user: automator
          ansible_host: vault20.of.worlds.com
          ansible_ssh_pass: "{{ vault20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ vault20_automator }}"
    ftpservers:
      hosts:
        ftp20:
          ansible_user: automator
          ansible_host: ftp20.of.worlds.com
          ansible_ssh_pass: "{{ ftp20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ ftp20_automator }}"
    mailservers:
      hosts:
        ms20:
          ansible_user: automator
          ansible_host: ms20.of.worlds.com
          ansible_ssh_pass: "{{ ms20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ ms20_automator}}"
    keycloak:
      hosts:
        kc20:
          ansible_user: automator
          ansible_host: kc20.of.worlds.com
          ansible_ssh_pass: "{{ kc20_automator }}"
          ansible_become: True
          ansible_become_method: sudo
          ansible_become_password: "{{ kc20_automator }}"
