- name: Ensure required packages are installed
  yum:
    name: "{{ chrony_required_packages }}"
    state: installed
  when: ansible_os_family == "RedHat"

- name: Ensure required packages are installed
  apt:
    name: "{{ chrony_required_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure chrony packages are installed
  yum:
    name: "{{ chrony_packages }}"
    state: installed
  when: ansible_os_family == "RedHat"

- name: Ensure chrony packages are installed
  apt:
    name: "{{ chrony_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Copy the chrony.conf
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_configfile_path }}"
    owner: root
    group: root
    mode: 0664
  notify: restart chrony

- name: Ensure chrony services is started and enabled at boot
  service:
    name: "{{ chrony_service_name }}"
    state: started
    enabled: yes
